/** Declaration file generated by dts-gen */

export = text_table;

declare function text_table(rows_: any, opts: any): any;

declare namespace text_table {
    const prototype: {
    };

}

